-- MySQL Script generated by MySQL Workbench
-- Fri Sep 16 16:37:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema building_company
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema building_company
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `building_company` DEFAULT CHARACTER SET utf8;
USE `building_company`;

-- -----------------------------------------------------
-- Table `building_company`.`department_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_company`.`department_details`
(
    `dept_id`   INT          NOT NULL AUTO_INCREMENT,
    `dept_name` VARCHAR(50)  NOT NULL,
    `remarks`   VARCHAR(256) NULL,
    PRIMARY KEY (`dept_id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `building_company`.`staff_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_company`.`staff_position`
(
    `pos_id`   INT         NOT NULL AUTO_INCREMENT,
    `pos_name` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`pos_id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `building_company`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_company`.`address`
(
    `id`       INT          NOT NULL AUTO_INCREMENT,
    `citi`     VARCHAR(50)  NOT NULL,
    `street`   VARCHAR(50)  NULL,
    `building` VARCHAR(50)  NULL,
    `remark`   VARCHAR(256) NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `building_company`.`phone_number`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_company`.`phone_number`
(
    `id`           INT          NOT NULL AUTO_INCREMENT,
    `phone_number` VARCHAR(13)  NOT NULL,
    `remark`       VARCHAR(150) NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `building_company`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_company`.`clients`
(
    `id`           INT          NOT NULL AUTO_INCREMENT,
    `first_name`   VARCHAR(50)  NOT NULL,
    `lastname`     VARCHAR(50)  NOT NULL,
    `phone_number` VARCHAR(13)  NOT NULL,
    `company_name` VARCHAR(100) NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `building_company`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_company`.`projects`
(
    `id`          INT         NOT NULL AUTO_INCREMENT,
    `name`        VARCHAR(50) NOT NULL,
    `assigned_to` INT         NOT NULL,
    `create_by`   INT         NOT NULL,
    `create_date` DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `end_date`    DATE        NULL,
    `client_id`   INT         NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `assigned_to_fk_idx` (`assigned_to` ASC) VISIBLE,
    INDEX `fk_projects_clients1_idx` (`client_id` ASC) VISIBLE,
    INDEX `fk_projects_create_by_idx` (`create_by` ASC) VISIBLE,
    CONSTRAINT `assigned_to_fk`
        FOREIGN KEY (`assigned_to`)
            REFERENCES `building_company`.`staff` (`staff_id`)
            ON DELETE CASCADE
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_projects_clients1`
        FOREIGN KEY (`client_id`)
            REFERENCES `building_company`.`clients` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_projects_create_by`
        FOREIGN KEY (`create_by`)
            REFERENCES `building_company`.`staff` (`staff_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `building_company`.`crews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_company`.`crews`
(
    `id`         INT NOT NULL,
    `project_id` INT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_crews_projects1_idx` (`project_id` ASC) VISIBLE,
    CONSTRAINT `fk_crews_projects1`
        FOREIGN KEY (`project_id`)
            REFERENCES `building_company`.`projects` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `building_company`.`salaries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_company`.`salaries`
(
    `id`     INT    NOT NULL AUTO_INCREMENT,
    `salary` DOUBLE NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `building_company`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_company`.`staff`
(
    `staff_id`        INT         NOT NULL AUTO_INCREMENT,
    `first_name`      VARCHAR(50) NOT NULL,
    `last_name`       VARCHAR(50) NOT NULL,
    `start_date`      DATE        NOT NULL,
    `end_date`        DATE        NULL,
    `dept_id`         INT         NOT NULL,
    `pos_id`          INT         NOT NULL,
    `address_id`      INT         NOT NULL,
    `phone_number_id` INT         NOT NULL,
    `crews_id`        INT         NULL,
    `salaries_id`     INT         NOT NULL,
    PRIMARY KEY (`staff_id`),
    INDEX `dept_id_fk_idx` (`dept_id` ASC) VISIBLE,
    INDEX `pos_id_fk_idx` (`pos_id` ASC) VISIBLE,
    INDEX `fk_staff_address1_idx` (`address_id` ASC) VISIBLE,
    INDEX `fk_staff_phone_number1_idx` (`phone_number_id` ASC) VISIBLE,
    INDEX `fk_staff_crews1_idx` (`crews_id` ASC) VISIBLE,
    INDEX `fk_staff_salaries1_idx` (`salaries_id` ASC) VISIBLE,
    CONSTRAINT `dept_id_fk`
        FOREIGN KEY (`dept_id`)
            REFERENCES `building_company`.`department_details` (`dept_id`)
            ON DELETE CASCADE
            ON UPDATE NO ACTION,
    CONSTRAINT `pos_id_fk`
        FOREIGN KEY (`pos_id`)
            REFERENCES `building_company`.`staff_position` (`pos_id`)
            ON DELETE CASCADE
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_staff_address1`
        FOREIGN KEY (`address_id`)
            REFERENCES `building_company`.`address` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_staff_phone_number1`
        FOREIGN KEY (`phone_number_id`)
            REFERENCES `building_company`.`phone_number` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_staff_crews1`
        FOREIGN KEY (`crews_id`)
            REFERENCES `building_company`.`crews` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_staff_salaries1`
        FOREIGN KEY (`salaries_id`)
            REFERENCES `building_company`.`salaries` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `building_company`.`bills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_company`.`bills`
(
    `bill_id`    INT      NOT NULL AUTO_INCREMENT,
    `amount`     DOUBLE   NOT NULL,
    `bill_date`  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `from_date`  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `to_date`    DATE     NULL,
    `paid_date`  DATE     NULL,
    `client_id`  INT      NOT NULL,
    `project_id` INT      NULL,
    PRIMARY KEY (`bill_id`),
    INDEX `fk_bills_clients1_idx` (`client_id` ASC) VISIBLE,
    INDEX `fk_bills_projects1_idx` (`project_id` ASC) VISIBLE,
    CONSTRAINT `fk_bills_clients1`
        FOREIGN KEY (`client_id`)
            REFERENCES `building_company`.`clients` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_bills_projects1`
        FOREIGN KEY (`project_id`)
            REFERENCES `building_company`.`projects` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `building_company`.`machines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_company`.`machines`
(
    `id`       INT          NOT NULL AUTO_INCREMENT,
    `name`     VARCHAR(50)  NOT NULL,
    `remark`   VARCHAR(256) NULL,
    `crews_id` INT          NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_machines_crews1_idx` (`crews_id` ASC) VISIBLE,
    CONSTRAINT `fk_machines_crews1`
        FOREIGN KEY (`crews_id`)
            REFERENCES `building_company`.`crews` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
